{
  "formatVersion": "1.1",
  "component": {
    "group": "demo",
    "module": "plugin",
    "version": "unspecified",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "firstdemo-0.0.1.jar",
          "url": "firstdemo-0.0.1.jar",
          "size": 12379,
          "sha512": "ade8ffdbd2c63099dd3894023882ece132c3a3517e6aabcdfc51fdf45354783103594689cd3120776087ffd4d4c64d5915be97aa4deba7a4d8c303ab296618b5",
          "sha256": "fc8e30f4cdbb5385d4ba28aee56987f358b3b31cc26bd1a445eadba535ad961d",
          "sha1": "dcdb080f9ebd0a087838d5dbb42b8990e8384343",
          "md5": "713f76b58afd4a125b3c020cb1b90830"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.0.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.5.31"
          }
        },
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "1.26"
          }
        }
      ],
      "files": [
        {
          "name": "firstdemo-0.0.1.jar",
          "url": "firstdemo-0.0.1.jar",
          "size": 12379,
          "sha512": "ade8ffdbd2c63099dd3894023882ece132c3a3517e6aabcdfc51fdf45354783103594689cd3120776087ffd4d4c64d5915be97aa4deba7a4d8c303ab296618b5",
          "sha256": "fc8e30f4cdbb5385d4ba28aee56987f358b3b31cc26bd1a445eadba535ad961d",
          "sha1": "dcdb080f9ebd0a087838d5dbb42b8990e8384343",
          "md5": "713f76b58afd4a125b3c020cb1b90830"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "firstdemo-0.0.1-javadoc.jar",
          "url": "firstdemo-0.0.1-javadoc.jar",
          "size": 261,
          "sha512": "d68cda28c6d319a52d751322123d879420f58e3e46410c6af6e82c850bc996a6b8a5d5718270c7becf0eb73e6bbca192cb42d226efa7790814dae8a3b92c49b4",
          "sha256": "0873a49ff76eb54cab19810d9fb6590b84cc0c9de9ff657aca37d1466360f8bc",
          "sha1": "fb1fe96e64b72e63e38fa19c8bfef99c6ab04d3e",
          "md5": "a542a160a0f29200f374b867888cb9e4"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "firstdemo-0.0.1-sources.jar",
          "url": "firstdemo-0.0.1-sources.jar",
          "size": 2402,
          "sha512": "3d8298bdba5efade42705f50425b7b194501ce475db1ebe5053c3283b73187e9089dacf69aa7dcf1c051ab7bbfb4783f6a4ab768a86288a9fd76db29e00c01b9",
          "sha256": "071563dd697d8631190284685036d51ea2e079e64104b97cabba0a9858f13180",
          "sha1": "278a991bb47749e43bc4a8a4666dfb3335326f49",
          "md5": "08f950a0e8ed4a76ff03243c56401e0d"
        }
      ]
    }
  ]
}
